-- CreateTable
CREATE TABLE "public"."T_AJUSTE_PONTO" (
    "TAP_CD_PONTO" SERIAL NOT NULL,
    "TAP_NM_SOLICITACAO" TEXT,
    "TAP_NM_STATUS" TEXT,
    "TAP_NM_DESCRICAO" TEXT,
    "TAP_NM_URL" TEXT,
    "TAP_DT_INICIAL" TIMESTAMP(3),
    "TAP_DT_FINAL" TIMESTAMP(3),
    "TAP_BL_APROVADO" BOOLEAN,

    CONSTRAINT "PK__T_AJUSTE__805AB33A83DE36FD" PRIMARY KEY ("TAP_CD_PONTO")
);

-- CreateTable
CREATE TABLE "public"."T_FUNCIONARIO" (
    "FUN_CD_USUARIO" SERIAL NOT NULL,
    "FUN_NM_NOME" TEXT,
    "FUN_NM_EMAIL" TEXT,
    "FUN_NM_SENHA" TEXT,
    "FUN_DT_CRIACAO" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "FUN_DT_MODIFICACAO" TIMESTAMP(3),

    CONSTRAINT "PK__T_FUNCIO__84C1360CCFBEA8D2" PRIMARY KEY ("FUN_CD_USUARIO")
);

-- CreateTable
CREATE TABLE "public"."T_PONTO" (
    "PON_CD_PONTO" SERIAL NOT NULL,
    "PON_NM_PONTO" TEXT,
    "PON_NM_ENDERECO" TEXT,
    "PON_CD_USUARIO" INTEGER,
    "PON_DT_PONTO" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "PON_DT_MODIFICACAO" TEXT,

    CONSTRAINT "PK__T_PONTO__0CF3ECE03A7FF45A" PRIMARY KEY ("PON_CD_PONTO")
);

-- CreateIndex
CREATE UNIQUE INDEX "UQ__T_AJUSTE__805AB33BF72022D4" ON "public"."T_AJUSTE_PONTO"("TAP_CD_PONTO");

-- CreateIndex
CREATE UNIQUE INDEX "UQ__T_FUNCIO__84C1360D7B241534" ON "public"."T_FUNCIONARIO"("FUN_CD_USUARIO");

-- CreateIndex
CREATE UNIQUE INDEX "UQ__T_PONTO__0CF3ECE152AD1002" ON "public"."T_PONTO"("PON_CD_PONTO");
