BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[T_AJUSTE_PONTO] (
    [TAP_CD_PONTO] INT NOT NULL IDENTITY(1,1),
    [TAP_NM_SOLICITACAO] VARCHAR(255),
    [TAP_NM_STATUS] VARCHAR(255),
    [TAP_NM_DESCRICAO] VARCHAR(255),
    [TAP_NM_URL] VARCHAR(255),
    [TAP_DT_INICIAL] DATE,
    [TAP_DT_FINAL] DATE,
    [TAP_BL_APROVADO] BIT,
    CONSTRAINT [PK__T_AJUSTE__805AB33A83DE36FD] PRIMARY KEY CLUSTERED ([TAP_CD_PONTO]),
    CONSTRAINT [UQ__T_AJUSTE__805AB33BF72022D4] UNIQUE NONCLUSTERED ([TAP_CD_PONTO])
);

-- CreateTable
CREATE TABLE [dbo].[T_FUNCIONARIO] (
    [FUN_CD_USUARIO] INT NOT NULL IDENTITY(1,1),
    [FUN_NM_NOME] VARCHAR(255),
    [FUN_NM_EMAIL] VARCHAR(255),
    [FUN_NM_SENHA] VARCHAR(255),
    [FUN_DT_CRIACAO] DATETIME CONSTRAINT [T_FUNCIONARIO_FUN_DT_CRIACAO_df] DEFAULT CURRENT_TIMESTAMP,
    [FUN_DT_MODIFICACAO] DATETIME,
    CONSTRAINT [PK__T_FUNCIO__84C1360CCFBEA8D2] PRIMARY KEY CLUSTERED ([FUN_CD_USUARIO]),
    CONSTRAINT [UQ__T_FUNCIO__84C1360D7B241534] UNIQUE NONCLUSTERED ([FUN_CD_USUARIO])
);

-- CreateTable
CREATE TABLE [dbo].[T_PONTO] (
    [PON_CD_PONTO] INT NOT NULL IDENTITY(1,1),
    [PON_NM_PONTO] VARCHAR(255),
    [PON_NM_ENDERECO] VARCHAR(255),
    [PON_CD_USUARIO] INT,
    [PON_DT_PONTO] DATETIME,
    [PON_DT_MODIFICACAO] VARCHAR(255),
    CONSTRAINT [PK__T_PONTO__0CF3ECE03A7FF45A] PRIMARY KEY CLUSTERED ([PON_CD_PONTO]),
    CONSTRAINT [UQ__T_PONTO__0CF3ECE152AD1002] UNIQUE NONCLUSTERED ([PON_CD_PONTO])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
